"""Discover/analyze lifecycle states + directory status.

Autogenerated then adjusted — alembic cannot diff MySQL ENUMs, so the ENUM ALTERs and data remaps below were added by hand and the falsely-flagged index drops removed.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = "008"
down_revision: Union[str, None] = "007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_FILE_STATUS_OLD = (
    "pending",
    "reading",
    "ai_queued",
    "enriching",
    "enriched",
    "accepted",
    "rejected",
    "failed",
)
_FILE_STATUS_NEW = (
    "pending",
    "reading",
    "read",
    "ai_queued",
    "analyze_queued",
    "enriching",
    "enriched",
    "accepted",
    "rejected",
    "failed",
    "missing",
)
_ENRICHMENT_TRIGGER_OLD = ("scan", "user_directory", "user_file", "retry")
_ENRICHMENT_TRIGGER_NEW = ("scan", "user_file", "retry")


def upgrade() -> None:
    op.add_column(
        "directories",
        sa.Column(
            "status",
            mysql.ENUM("active", "missing", name="directory_status"),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
    )
    # Backfill is explicit for any row predating the column server_default.
    op.execute("UPDATE directories SET status = 'active' WHERE status IS NULL")

    op.alter_column(
        "file_records",
        "status",
        existing_type=mysql.ENUM(*_FILE_STATUS_OLD, name="file_status"),
        type_=mysql.ENUM(*_FILE_STATUS_NEW, name="file_status"),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'"),
    )
    # Stuck rows queued under the old overloaded transient never drained; move them
    # onto the durable analyze queue so the new drain finally claims them after deploy.
    op.execute(
        "UPDATE file_records SET status = 'analyze_queued' WHERE status = 'ai_queued'"
    )

    # user_directory was dead; remap any surviving rows so the narrowed ENUM ALTER
    # does not truncate them (`trigger` is a MySQL reserved word — backtick it).
    op.execute(
        "UPDATE enrichment_runs SET `trigger` = 'user_file' "
        "WHERE `trigger` = 'user_directory'"
    )
    op.alter_column(
        "enrichment_runs",
        "trigger",
        existing_type=mysql.ENUM(*_ENRICHMENT_TRIGGER_OLD, name="enrichment_trigger"),
        type_=mysql.ENUM(*_ENRICHMENT_TRIGGER_NEW, name="enrichment_trigger"),
        existing_nullable=False,
    )


def downgrade() -> None:
    op.alter_column(
        "enrichment_runs",
        "trigger",
        existing_type=mysql.ENUM(*_ENRICHMENT_TRIGGER_NEW, name="enrichment_trigger"),
        type_=mysql.ENUM(*_ENRICHMENT_TRIGGER_OLD, name="enrichment_trigger"),
        existing_nullable=False,
    )

    op.execute(
        "UPDATE file_records SET status = 'ai_queued' WHERE status = 'analyze_queued'"
    )
    op.execute(
        "UPDATE file_records SET status = 'failed' WHERE status IN ('read', 'missing')"
    )
    op.alter_column(
        "file_records",
        "status",
        existing_type=mysql.ENUM(*_FILE_STATUS_NEW, name="file_status"),
        type_=mysql.ENUM(*_FILE_STATUS_OLD, name="file_status"),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'"),
    )

    op.drop_column("directories", "status")
