"""Widen isbn10/isbn13 and processing_logs.message to hold separator-bearing values (DMI-139)."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "009"
down_revision: Union[str, None] = "008"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerated; spurious drop_index ops for functional/DESC indexes the comparator cannot match were pruned after inspection.
    op.alter_column(
        "metadata",
        "isbn13",
        existing_type=mysql.CHAR(length=13),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "isbn10",
        existing_type=mysql.CHAR(length=10),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "processing_logs",
        "message",
        existing_type=mysql.VARCHAR(length=1024),
        type_=sa.Text(),
        existing_nullable=True,
    )


def downgrade() -> None:
    op.alter_column(
        "processing_logs",
        "message",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "isbn10",
        existing_type=sa.String(length=20),
        type_=mysql.CHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "metadata",
        "isbn13",
        existing_type=sa.String(length=20),
        type_=mysql.CHAR(length=13),
        existing_nullable=True,
    )
