"""Create ai_calls + ai_config_versions and add enrichment_runs.config_version_id (DMI-144)."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = "010"
down_revision: Union[str, None] = "009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


AI_CALL_ORIGIN_VALUES = ("pipeline", "sandbox")
AI_CALL_TIER_VALUES = ("cheap", "expensive")


def upgrade() -> None:
    # Autogenerated; spurious drop/create_index ops for functional/DESC indexes the comparator cannot match (cf. migration 009) were pruned.
    op.create_table(
        "ai_config_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("cheap_model", sa.String(length=64), nullable=False),
        sa.Column("expensive_model", sa.String(length=64), nullable=False),
        sa.Column("effort", sa.String(length=16), nullable=False),
        sa.Column("escalation_threshold", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "provider",
            sa.String(length=32),
            server_default="openai",
            nullable=False,
        ),
        sa.Column("response_format_ref", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uq_ai_config_versions_version"),
    )
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("enrichment_run_id", sa.Integer(), nullable=True),
        sa.Column("config_version_id", sa.Integer(), nullable=True),
        sa.Column(
            "origin",
            mysql.ENUM(*AI_CALL_ORIGIN_VALUES, name="ai_call_origin"),
            nullable=False,
        ),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column(
            "tier",
            mysql.ENUM(*AI_CALL_TIER_VALUES, name="ai_call_tier"),
            nullable=False,
        ),
        sa.Column("is_canonical", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("effort", sa.String(length=16), nullable=True),
        sa.Column("response_format_ref", sa.String(length=64), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_prompt", mysql.LONGTEXT(), nullable=False),
        sa.Column("raw_response", mysql.LONGTEXT(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("parse_errors", mysql.JSON(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(fsp=3),
            server_default=sa.text("CURRENT_TIMESTAMP(3)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_version_id"], ["ai_config_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["enrichment_run_id"], ["enrichment_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file_records.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_calls_file_created", "ai_calls", ["file_id", sa.text("created_at DESC")])
    op.create_index(
        "ix_ai_calls_file_run_sequence",
        "ai_calls",
        ["file_id", "enrichment_run_id", "sequence"],
    )
    op.add_column(
        "enrichment_runs",
        sa.Column("config_version_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "fk_enrichment_runs_config_version_id",
        "enrichment_runs",
        "ai_config_versions",
        ["config_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_enrichment_runs_config_version_id", "enrichment_runs", type_="foreignkey"
    )
    op.drop_column("enrichment_runs", "config_version_id")
    # Index drops are implicit in drop_table; MariaDB refuses an explicit drop while the
    # file_id FK still relies on ix_ai_calls_file_created as its supporting index.
    op.drop_table("ai_calls")
    op.drop_table("ai_config_versions")
