"""Seed ai_config_versions v1 — hand-written DATA migration (op.bulk_insert), not autogenerated DDL (DMI-144)."""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.ai.prompt.book_metadata import build_system_prompt

revision: str = "011"
down_revision: Union[str, None] = "010"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ai_config_versions = sa.table(
        "ai_config_versions",
        sa.column("version", sa.Integer),
        sa.column("label", sa.String),
        sa.column("system_prompt", sa.Text),
        sa.column("cheap_model", sa.String),
        sa.column("expensive_model", sa.String),
        sa.column("effort", sa.String),
        sa.column("escalation_threshold", sa.Numeric),
        sa.column("provider", sa.String),
        sa.column("response_format_ref", sa.String),
        sa.column("is_active", sa.Boolean),
    )
    op.bulk_insert(
        ai_config_versions,
        [
            {
                "version": 1,
                "label": "v1",
                # Imported at runtime so the seed never drifts from the code it snapshots.
                "system_prompt": build_system_prompt(),
                # cheap == expensive keeps escalation inert until a real model is set via DB/UI.
                "cheap_model": "gpt-4o-mini",
                "expensive_model": "gpt-4o-mini",
                "effort": "high",
                "escalation_threshold": 0.7,
                "provider": "openai",
                "response_format_ref": "book_metadata.v2",
                "is_active": True,
            }
        ],
    )


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM ai_config_versions WHERE version = 1"))
